
# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

build:
  image: latest

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

conda:
  environment: docs/readthedocs-environment.yml

python:
   version: 3.6
   install:
      - method: pip
        path: .

